relativeURLs = true
baseURL = 'https://redviking121.github.io/vaults/'
languageCode = 'en-us'

title = 'My Digital Garden'
theme = 'PaperMod'

[params]
  defaultTheme = "dark"
  enableInlineShortcodes = true
  mainSections = ["posts"]
  showHomePosts = true

  [params.homeInfoParams]
    Title = "Welcome to my Garden"
    Content = "A collection of thoughts, notes, and research."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/redviking121/vaults"
